name: prohealth360_daktari
version: 1.0.0
description: UoNAfyaApp360 Daktari Application
repository: https://github.com/savannahghi/AfyaMoja.git
issue_tracker: https://github.com/savannahghi/AfyaMoja/issues
documentation: https://github.com/savannahghi/AfyaMoja/tree/main/docs
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  async_redux: ^18.0.2
  connectivity_plus: ^2.3.6+1
  debug_logger: ^0.0.23
  firebase_analytics: ^10.0.5
  firebase_core: ^2.2.0
  firebase_messaging: ^14.1.0
  flutter:
    sdk: flutter
  flutter_config: ^2.0.0
  flutter_html: ^3.0.0-alpha.5
  flutter_local_notifications: ^12.0.3+1
  flutter_localizations:
    sdk: flutter
  flutter_pdfview: ^1.2.5
  flutter_svg: ^1.1.6
  freezed: ^2.1.0+1
  freezed_annotation: ^2.0.3
  http: ^0.13.5
  intl: ^0.17.0
  json_annotation: ^4.5.0
  json_serializable: ^6.3.1
  overlay_support: ^2.0.1
  path: ^1.8.2
  quiver: ^3.1.0
  rxdart: ^0.27.5
  sentry_flutter: ^6.15.1
  sghi_core: ^0.2.8
  sms_autofill: ^2.2.0
  sqflite: ^2.0.3+1
  stream_chat_flutter: ^5.1.0
  unicons: ^2.1.0
  url_launcher: ^6.1.6

dev_dependencies:
  build_runner: ^2.2.0
  built_value_generator: ^8.4.1
  connectivity_plus_platform_interface: ^1.2.1
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0
  lint: ^1.10.0
  mockito: ^5.3.0
  mocktail_image_network: ^0.3.1
  plugin_platform_interface: ^2.1.2

flutter:
  uses-material-design: true
  assets:
    - google_fonts/
    - assets/
    - assets/images/
    - assets/icons/
